In [34]:
#1.	Array Creation

In [35]:
#Create a 1D array of numbers from 10 to 50.
import numpy as np
a=np.arange(10,51)
a.ndim
a

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

In [36]:
#2. Create a 3x3 array of random numbers between 0 and 1.

In [37]:
r = np.random.rand(3, 3)
r

array([[0.12679477, 0.96537847, 0.51316807],
       [0.02728447, 0.93942833, 0.26794464],
       [0.25247945, 0.33333932, 0.61777824]])

In [38]:
#Find the shape, size, and data type of the array you created in the previous task.
print("shape of array",a.shape)
print("size of the array",a.size)
print("data type of the array",a.dtype)
print("dimension of the array",a.ndim)

shape of array (41,)
size of the array 41
data type of the array int64
dimension of the array 1


In [39]:
#3. Basic Operations

In [40]:
#Add 5 to every element of a 1D array.
arr1=np.array([1,2,3])
arr1+5


array([6, 7, 8])

In [41]:
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])
arr1 * arr2

array([[ 5, 12],
       [21, 32]])

In [42]:
#4.	Indexing and Slicing

In [43]:
#Create a 5x5 array of integers from 1 to 25. Extract:
# The first row.
# The last column.
# A subarray of the first three rows and first two columns.

a= np.arange(1, 26).reshape(5, 5)
print(a)
print("first row",a[0, :])
print("last column",a[:, -1])
print("subarray", a[:3, :2])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
first row [1 2 3 4 5]
last column [ 5 10 15 20 25]
subarray [[ 1  2]
 [ 6  7]
 [11 12]]


In [44]:
#5.	Aggregation

In [45]:
# Create a 10-element array of random integers between 1 and 100. Find:
# The maximum value.
# The minimum value.
# The mean and standard deviation.

a = np.random.randint(1, 101, size=10)
print("Maximum value:", np.max(a))
print("Minimum value:", np.min(a))
print("Mean:", np.mean(a))
print("Standard deviation:", np.std(a))

Maximum value: 96
Minimum value: 8
Mean: 53.4
Standard deviation: 32.293033304414124


In [46]:
#6.	Reshaping

In [47]:
#Convert a 1D array of numbers from 1 to 12 into a 3x4 matrix.
c = np.arange(1, 13)
c.reshape(3, 4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [48]:
#7.	Broadcasting

In [49]:
#Create a 3x3 matrix of ones. Add a 1D array [1, 2, 3] to each row.
a = np.ones((3, 3), dtype=int)
b= np.array([1, 2, 3])
a+b

array([[2, 3, 4],
       [2, 3, 4],
       [2, 3, 4]])

In [50]:
#8.	Filtering

In [51]:
#Create a 1D array of random integers between 1 and 50. Extract all elements that are divisible by 5.
a=np.arange(1,51)
divisible_by_5 = a[a % 5 == 0]

print("Original array:", a)
print("Elements divisible by 5:", divisible_by_5)

Original array: [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
 49 50]
Elements divisible by 5: [ 5 10 15 20 25 30 35 40 45 50]


In [52]:
#9.	Matrix Multiplication

In [53]:
#Create two 2x2 matrices and perform matrix multiplication.
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])
a=np.dot(arr1,arr2)
a

array([[19, 22],
       [43, 50]])

In [54]:
#10.	Advanced Indexing

In [55]:
# Given a 4x4 array, use fancy indexing to extract the diagonal elements.
arr = np.arange(16).reshape(4, 4)
diagonal_elements = arr[[0, 1, 2, 3], [0, 1, 2, 3]]
print("Original array:\n", arr)
print("Diagonal elements:", diagonal_elements)

Original array:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
Diagonal elements: [ 0  5 10 15]
